color background   default   default
color info         default   black
color article      default   default
color listnormal_unread white default
color listnormal green default
color listfocus  black yellow
color listfocus_unread  black yellow

# highlights
highlight article "^(Title):.*$" blue default
highlight article "https?://[^ ]+" red default
highlight article "\\[image\\ [0-9]+\\]" green default
