#!/usr/bin/env bash

source $HOME/dotfiles/deathmaz/executable/scripts/bin/fulltext-rss.sh

w3m_tab() {
  kitty @ launch --type=tab w3m "$1" \
    && kitty @ launch \
    && kitty @ focus-window --match 'title:^w3m'
}

read_w3m() {
  readable "$1" -p html-title,html-content > /tmp/readable.html \
    && w3m_tab /tmp/readable.html
}

media() {
  nohup mpv-custom "$1" > /dev/null 2>&1 &
}

media_queue() {
  $MAZ_TASK_SPOOLER_COMMAND mpv-custom "$1"
}

image() {
  nohup feh "$1" > /dev/null 2>&1 &
}

LINK="$1"
# A function containing a case list of options
Open() {
  case "$LINK" in
    # *youtube.com*|*gfycat.com*|*v.redd.it*|*twitch.tv*|*youtu.be*|*vodlocker.com*|*.webm*|*.mp4*|*.avi) TS_SOCKET=/tmp/newsboat ts mpv-custom "$1";;
    # *reddit.com*) tmux split-window -h -e MAZ_DISABLE_EXTENSION=1 && tmux send-keys "tuir -l $1 && tmux kill-pane " 'Enter';;
    # *i.imgur.com*\.gifv) tmux split-window -h -e MAZ_DISABLE_EXTENSION=1 && tmux send-keys "mpv-custom ${1/gifv/mp4} && tmux kill-pane" 'Enter';;
    *life.pravda.com.ua*)
      read_fulltext "$LINK"
      ;;
    *politico*)
      read_fulltext "$LINK"
      ;;
    *nv.ua*)
      read_fulltext "$LINK"
      ;;
    *economist.com*)
      read_fulltext "$LINK"
      ;;
    *theguardian.com*)
      read_fulltext "$LINK"
      ;;
    *tverezo.info*)
      read_fulltext "$LINK"
      ;;
    *defence-ua.com*)
      read_fulltext "$LINK"
      ;;
    *reuters*)
      read_fulltext "$LINK"
      ;;
    *nypost*)
      read_fulltext "$LINK"
      ;;
    *news.yahoo*)
      read_fulltext "$LINK"
      ;;
    *polygraph*)
      read_fulltext "$LINK"
      ;;
    *pics.livejournal.com*)
      image "$LINK"
      ;;
    *livejournal.com*)
      read_fulltext "$LINK"
      ;;
    *ndtv.com*)
      read_fulltext "$LINK"
      ;;
    *nytimes.com*)
      read_fulltext "$LINK"
      ;;
    *19fortyfive.com*)
      read_fulltext "$LINK"
      ;;
    *images.jpost.com*)
      image "$LINK"
      ;;
    *jpost.com*)
      read_fulltext "$LINK"
      ;;
    *radiosvoboda.org*)
      read_fulltext "$LINK"
      ;;
    *pravda.com.ua*)
      read_fulltext "$LINK"
      ;;
    *zn.ua*)
      read_fulltext "$LINK"
      ;;
    *focus.ua*)
      read_fulltext "$LINK"
      ;;
    *wsj.com*)
      read_fulltext "$LINK"
      ;;
    *usnews.com*)
      read_fulltext "$LINK"
      ;;
    *dw.com*)
      read_fulltext "$LINK"
      ;;
    *aljazeera.com*)
      read_fulltext "$LINK"
      ;;
    *dailymail.co*)
      read_fulltext "$LINK"
      ;;
    *telegraph.co*)
      read_fulltext "$LINK"
      ;;
    *forbes.com*)
      read_fulltext "$LINK"
      ;;
    *19fortyfive.com*)
      read_fulltext "$LINK"
      ;;
    *bbc.co*)
      read_fulltext "$LINK"
      ;;
    *washingtonpost.com*)
      read_fulltext "$LINK"
      ;;
    *rbc.ua*)
      read_fulltext "$LINK"
      ;;
    *independent.co*)
      read_fulltext "$LINK"
      ;;
    *huffpost.com*)
      read_fulltext "$LINK"
      ;;
    *unian*)
      read_fulltext "$LINK"
      ;;
    *liga.net*)
      read_fulltext "$LINK"
      ;;
    *rusi.org*)
      read_fulltext "$LINK"
      ;;
    *ain.ua*)
      read_fulltext "$LINK"
      ;;
    *preview.redd.it*)
      image "$LINK"
      ;;
    *img.thedailybeast.com/image*)
      image "$LINK"
      ;;
    *zn.ua/img*)
      media "$LINK"
      ;;
    *reddit.com/link/*/video*)
      LINK="$(lynx -source "$LINK" | grep -oP 'data-mpd-url="\K[^"]+')"
      media "$LINK"
      ;;
    *reddit.com*)
      kitty @ launch --type=tab tuir -l "$LINK"
      ;;
    *gfycat.com/*|*.gif)
      nohup mpv-custom "${LINK/.gifv/.webm}" > /dev/null 2>&1 &
      ;;
    *giphy.com*)
      media "$LINK"
      ;;
    *imgur.com/*.gifv|*imgur.com/*.mp4|*imgur.com/*.webm|*imgur.com/*.gif|*.webp)
      media "$LINK"
      ;;
    *v.redd.it/*)
      media "$LINK"
      ;;
    *.mp3)
      media "$LINK"
      ;;
    *telegram-cdn.org/file*|*cdn-telegram.org/file*)
      media "$LINK"
      ;;
    *video.twimg.com*)
      media "$LINK"
      ;;
    *.mp4|*.mkv|*.avi|*.wmv|*.m4v|*.mpg|*.mpeg|*.flv|*.ogm|*.ogv|*.gifv)
      media "$LINK"
      ;;
    *instagram.com/p/*)
      media "$LINK"
      ;;
    # *instagram.com/p/*)
    #   LINK="$(curl -s "$LINK" | grep -oP '<meta property="og:image" content="\K[^"]+')"
    #   image "$LINK"
    #   ;;
    *youtube.com*|*twitch.tv*|*youtu.be*|*vodlocker.com*|*.webm*)
      media "$LINK"
      ;;
    *.jpg|*.png|*.jpeg|*nitter.*/pic*|*pbs.twimg.com/media*)
      image "$LINK"
      ;;
    # *nitter.*)
    #   w3m_tab "$LINK"
    #   ;;
    # *) readable "$1" -p html-title,html-content > /tmp/readable.html ; $MAZ_CLI_BROWSER -no-connect /tmp/readable.html;
    *)
    xdg-open "$LINK"
    ;;
  esac
}

# Now a for loop to iterate the list of options,
for url; do
  Open "$url"
done
