#!/bin/sh
# elvis: search

. surfraw || exit 1

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
	w3_browse_url "https://search.inetol.net/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://search.inetol.net/search?q=${escaped_args}&language=auto"
fi
