# the keyboard devices it reads from, if no devices are specified, it reads from all
devices:
# - "/dev/input/by-id/SOME_KEYBOARD_REPLACE_ME-event-kbd"

# this is executed when mouseless starts, e.g. useful for setting the keyboard layout
# startCommand: "setxkbmap de"

# the default speed for mouse movement and scrolling
# baseMouseSpeed: 750.0
baseMouseSpeed: 250.0
baseScrollSpeed: 20.0

# the time it takes to accelerate to baseMouseSpeed (in ms), 0 to reach top speed immediately
# mouseAccelerationTime: 200.0
mouseAccelerationTime: 0
# the shape of the acceleration curve, 1.0 is linear, higher values have more time at low speeds
mouseAccelerationCurve: 2.0
# speed of the mouse when it starts moving
startMouseSpeed: 0.0
# same for deceleration
# mouseDecelerationTime: 300.0
# mouseDecelerationCurve: 3.0

# the rest of the config defines the layers with their bindings
layers:
# the first layer is active at start
- name: initial
  bindings:
    tab: tap-hold-next tab ; toggle-layer mouse ; 1000
    rightmeta: rightctrl
    f2: volumedown
    f3: volumeup
# a layer for mouse movement
- name: mouse
  # when true, keys that are not mapped keep their original meaning
  passThrough: true
  bindings:
    # quit mouse layer
    q: layer initial
    # keep the mouse layer active
    grave: layer mouse
    r: reload-config
    l: move  1  0
    j: move  0  1
    k: move  0  -1
    h: move  -1  0
    p: scroll up
    n: scroll down
    leftalt: speed 2.0
    leftshift: speed 3.0
    space: speed 0.3
    e: speed 0.3
    f: button left
    d: button middle
    s: button right
    k0: "exec xdotool mousemove 0 0"
    w: rightctrl+rightalt+w
    i: rightctrl+rightalt+i
    m: rightctrl+rightalt+m
    c: rightctrl+rightalt+c
    v: rightctrl+rightalt+v
    x: rightctrl+w
